"""Generalized Additive Models for Location, Scale and Shape in PyTorch."""

from torchgamlss.diagnostics import (
    BucketPlotPanel,
    BucketPlotResult,
    BucketStatistics,
    ModelDiagnostics,
    QuantileResidualSummary,
    ResidualDiagnosticPlot,
    WormPlotPanel,
    WormPlotResult,
    bucket_plot,
    compare_models,
    worm_plot,
)
from torchgamlss.families import (
    BCCG,
    BCPE,
    BCT,
    GG,
    IG,
    LOGNO,
    PE,
    TF,
    WEI,
    Beta,
    BoxCoxColeGreen,
    BoxCoxPowerExponential,
    BoxCoxT,
    CensoredFamily,
    CensoredResponse,
    Censoring,
    Family,
    Gamma,
    GeneralizedGamma,
    InverseGaussian,
    LogNormal,
    NegativeBinomial,
    Normal,
    Poisson,
    PowerExponential,
    StudentT,
    TruncatedFamily,
    Weibull,
)
from torchgamlss.fitting import CGControl, CGFitResult, RSControl, RSFitResult
from torchgamlss.formula import FormulaData
from torchgamlss.functionals import (
    SmoothCrossingBootstrapResult,
    SmoothDerivedBandResult,
    SmoothDerivedBootstrapResult,
    SmoothExtremumBootstrapResult,
)
from torchgamlss.inference import (
    InferenceResult,
    SmoothBootstrapResult,
    SmoothInferenceResult,
    SmoothJointBandResult,
    SmoothJointBootstrapResult,
    SmoothJointInferenceBand,
    SmoothJointInferenceResult,
    SmoothSimultaneousBand,
)
from torchgamlss.links import IdentityLink, InverseLink, Link, LogitLink, LogLink
from torchgamlss.model import GAMLSS, FitResult, TermContributions
from torchgamlss.optimization import (
    MiniBatchControl,
    MiniBatchFitResult,
    MiniBatchValidationData,
)
from torchgamlss.penalties import (
    PenalizedLeastSquaresResult,
    solve_penalized_least_squares,
)
from torchgamlss.predictors import MLPPredictor, SharedMLPPredictor
from torchgamlss.quantiles import (
    QuantileBandResult,
    QuantileBootstrapResult,
    QuantilePrediction,
)
from torchgamlss.smooths import PSpline, SmoothTerm
from torchgamlss.survival import SurvivalPrediction

__all__ = [
    "BCCG",
    "BCT",
    "BCPE",
    "Beta",
    "BoxCoxColeGreen",
    "BoxCoxPowerExponential",
    "BoxCoxT",
    "BucketPlotPanel",
    "BucketPlotResult",
    "BucketStatistics",
    "CGControl",
    "CGFitResult",
    "CensoredFamily",
    "CensoredResponse",
    "Censoring",
    "Family",
    "FitResult",
    "FormulaData",
    "GAMLSS",
    "Gamma",
    "GeneralizedGamma",
    "GG",
    "IG",
    "IdentityLink",
    "InferenceResult",
    "InverseGaussian",
    "InverseLink",
    "Link",
    "LogLink",
    "LOGNO",
    "LogNormal",
    "LogitLink",
    "ModelDiagnostics",
    "MiniBatchControl",
    "MiniBatchFitResult",
    "MiniBatchValidationData",
    "MLPPredictor",
    "NegativeBinomial",
    "Normal",
    "Poisson",
    "PowerExponential",
    "PE",
    "PenalizedLeastSquaresResult",
    "PSpline",
    "QuantileBandResult",
    "QuantileBootstrapResult",
    "QuantilePrediction",
    "QuantileResidualSummary",
    "RSControl",
    "RSFitResult",
    "ResidualDiagnosticPlot",
    "SmoothBootstrapResult",
    "SmoothCrossingBootstrapResult",
    "SmoothDerivedBandResult",
    "SmoothDerivedBootstrapResult",
    "SmoothExtremumBootstrapResult",
    "SmoothInferenceResult",
    "SmoothJointBandResult",
    "SmoothJointBootstrapResult",
    "SmoothJointInferenceBand",
    "SmoothJointInferenceResult",
    "SmoothSimultaneousBand",
    "SmoothTerm",
    "SharedMLPPredictor",
    "TermContributions",
    "StudentT",
    "SurvivalPrediction",
    "TF",
    "TruncatedFamily",
    "WEI",
    "Weibull",
    "WormPlotPanel",
    "WormPlotResult",
    "bucket_plot",
    "compare_models",
    "solve_penalized_least_squares",
    "worm_plot",
]

__version__ = "0.1.0a3.dev0"
